apiVersion: v1
kind: ConfigMap
metadata:
  name: runstate-config
  namespace: runstate
data:
  PORT: "3001"
  APP_ENV: "dev"

  MONITORING_STREAM: "betteruptime:website-ticks"
  MONITORING_REGION_NAME: "ap-south-1"
  MONITORING_GROUP: "monitoring-group"
  MONITORING_CONSUMER: "monitoring-consumer"

  STATUS_CHANGE_STREAM: "betteruptime:website-status-change"
  STATUS_CHANGE_GROUP: "status-change-group"
  STATUS_CHANGE_CONSUMER: "status-change-consumer"

  NOTIFICATION_STREAM: "betteruptime:website-status-notification"
  NOTIFICATION_GROUP: "notification-group"
  NOTIFICATION_CONSUMER: "notification-consumer"