apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: runstate-app-secret
  namespace: runstate
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore 
  target:
    name: runstate-app-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: runstate/prod/app