apiVersion: v1
kind: Service
metadata:
  name: runstate-api
  namespace: runstate
  labels:
    app: runstate-api
spec:
  selector:
    app: runstate-api
  ports:
    - name: http
      port: 80
      targetPort : 3001
  type: ClusterIP
