apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: runstate-api
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - runstate
  selector:
    matchLabels:
      app: runstate-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s