# Creates K8s Identity called argocd/argocd-image-updater
# Image Updater Pod will run as the ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-image-updater
  namespace: argocd
---

# A Role defines what this ServiceAccount is allowed to do inside the argocd namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-image-updater
  namespace: argocd
rules:
  - apiGroups: [""]
      resources: ["configmaps", "secrets", "events"]
      verbs: ["get", "list", "watch"]
  - apiGroups: [""]
      resources: ["events"]
      verbs: ["create"]
  - apiGroups: ["argoproj.io"]
      resources: ["applications"]
      verbs: ["get", "list", "watch", "update", "patch"]

---

# RoleBinding connects the role to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-image-updater
  namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-image-updater
subjects:
  - kind: ServiceAccount
    name: argocd-image-updater
    namespace: argocd

---

# It launches one pod running the Image Updater binary.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-image-updater
  template:
    metadata:
      labels:
        app: argocd-image-updater
    spec:
      serviceAccountName: argocd-image-updater
      containers:
        - name: argocd-image-updater
          image: ghcr.io/argoproj-labs/argocd-image-updater:v0.15.2 # Actual ArgoCD Image Updater container image.
          imagePullPolicy: IfNotPresent
          command: # This starts the updater in normal controller mode.
            - /app/argocd-image-updater
            - run
          env:
            - name: ARGOCD_SERVER # This tells Image Updater how to reach the ArgoCD API service inside the cluster.
              value: argocd-server.argocd.svc.cluster.local:80
            - name: ARGOCD_INSECURE # This tells it to use insecure mode when talking to ArgoCD.
              value: "true"
            - name: ARGOCD_GRPC_WEB # This enables grpc-web mode for communication with ArgoCD.
              value: "true"
            - name: GIT_COMMIT_USER # These are used when Image Updater writes changes back to Git.
              value: argocd-image-updater
            - name: GIT_COMMIT_EMAIL
              value: image-updater@runstate.local
          volumeMounts: # mount a ConfigMap into the container
            - name: config
              mountPath: /app/config
      volumes:
        - name: config
          configMap:
            name: argocd-image-updater-config
