# ArgoCD Application(s) Layer
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: runstate-root
  namespace: argocd # The ArgoCD control resource lives in the argocd namespace.
spec:
  project: default # no restrictions
  source: # where the k8 manifest live
    repoURL: git@github.com:RitikaxG/runstate-gitops.git
    targetRevision: main # which Git branch to watch
    path: apps/runstate # ArgoCD deploys everything in this folder.

  destination: # where to deploy
    server: https://kubernetes.default.svc # Deploy into the same cluster where ArgoCD runs.
    namespace: runstate

  syncPolicy: # This defines how ArgoCD keeps the cluster in sync with Git.
    automated:
      prune: true # If something exists in the cluster but not in Git, ArgoCD deletes it. Git is the source of truth.
      selfHeal: true # If someone manually changes something in the cluster. ArgoCD will revert it automatically.

    syncOptions:   # If the namespace doesn't exist, create it.
      - CreateNamespace=true