# Kubernetes → AWS IAM so the Cluster Autoscaler pod can call AWS APIs to scale your EKS node group.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  annotations: # When a pod uses this ServiceAccount, assume this IAM Role.
        eks.amazonaws.com/role-arn: arn:aws:iam::478043880457:role/runstate-cluster-autoscaler-role